# Generated by Django 2.1.5 on 2019-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='train_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
