# Generated by Django 2.1.5 on 2019-01-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='arival_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='depetrure_time',
            new_name='departure_time',
        ),
    ]
