# Generated by Django 2.1.5 on 2019-01-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190122_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='train_no',
            new_name='train',
        ),
    ]
